datasources:
  - name: data-base-1
    url: jdbc:postgresql://localhost:5432/db1
    table: users
    user: testuser1
    password: testpass1
    driver-class-name: org.postgresql.Driver
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  - name: data-base-2
    url: jdbc:postgresql://localhost:5432/db2
    table: user_table
    user: testuser2
    password: testpass2
    driver-class-name: org.postgresql.Driver
    mapping:
      id: ldap_login
      username: ldap_login
      name: name
      surname: surname

jpa:
  hibernate:
    ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
