spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db1
    username: testuser1
    password: testpass1
    driverClassName: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html